QoboLtd/cakephp-utils

- tests/TestCase/UtilityTest.php
Controller test was too specific, expecting the results from the
plugin's test application.  This works within the plugin, but
breaks application integration tests, where the namespaces of the
results are different.
Instead of expecting a particular class with the certain namespace,
we now look at the suffix only, which contains the actual class name.
> Fix unit test for integration testing (task #3495)

- src/Utility.php
- tests/TestCase/UtilityTest.php
Few useful methods added:
-  Get the list of all current models based on ConnectionManager. (with or without phinxlog tables).
- Get the list of model columns based on ConnectionManager.
> Adding getters for Models and its columns

- src/Utility.php
- tests/TestCase/UtilityTest.php
This method is useful for finding CSV modules (modules that have
configurations).  It'll be used from a number of places.
> Added findDirs() method

- src/Utility.php
Background should be equal to `$k` that represents HEX notation of the color.
> Fixed typo on color (task #3873)

- composer.json
Since we already use burzum/cakephp-file-storage, it makes sense
to keep them together, as they interoperate very frequently.  Having
one without another, and loading imagine plugin separately on the
application level or in another plugin seems confusion and
non-obvious.
> Added burzum/cakephp-imagine-plugin to composer

- composer.json
There are some behavioral changes in CakePHP 3.5 so we'll need
to update separately.
https://book.cakephp.org/3.0/en/appendices/3-5-migration-guide.html
For now, sticking to 3.4.
> Lock CakePHP to 3.4

- README.md
Some of the repository badges were pointing to the URLs of the
cakephp-csv-migrations plugin, instead of cakephp-utils.  Fixed.
> Updated README with corret badges

- webroot/js/dataTables.init.js
Until now, we silently report error in the browser console.
Once the things get more stable client-side, we'd replace
it with thowable behavior.
Reference: https://datatables.net/reference/event/error
> Replacing alerts with silent console messages (task #5024)

- composer.json
Locking CakePHP to v3.5.8 because of this [issue](https://github.com/cakephp/cakephp/issues/11577) caused by CakePHP v3.5.9 release. The [fix](https://github.com/cakephp/cakephp/pull/11578) has been merged and set for the next patch release, v3.5.10.
> Lock CakePHP to v3.5.8

- composer.json
This reverts commit c5ea769bf6b0efba832859207b7579b366383183.
> Revert "Lock CakePHP to v3.5.8"

- webroot/js/QoboStorage.js
By default, the plugin uses browser's SessionStorage, but you can use LocalStorage
by defining the `engine` option, as `local`, during instantiation.
To use the plugin simply instantiate it and use the public read/write methods:
```javascript
var storage = new QoboStorage(
{engine: 'local'}
);
storage.write('foo', 'bar');
var value = storage.read('foo');
alert(value); // 'bar'
```
> Storage wrapper plugin for browser's storage usage (task #5173)

- src/ModuleConfig/Parser/Schema/fields.json
Default values can vary depending on the field type - strings,
integers, floats, boolean, etc.
> Relaxed validation for default value of the field (task #5293)

- config/bootstrap.php
- src/Utility.php
- tests/TestCase/UtilityTest.php
* Moved global function `sizeToBytes()` from `config/bootstrap.php` to the `Utility::valueToBytes()`, leaving a backward-compatibility placeholder.
* Minor code changes for improved test coverage.
> Minor refactoring (task #5473)

- src/Utility.php
- tests/TestCase/UtilityTest.php
Converting value to bytes now supports negative values as well,
which is specifically handy for cases like PHP's `memory_limit=-1`.
> Support negative values in valueToBytes()

- composer.json
Changelogs summary:
- cakephp/cakephp downgraded from 3.6.1 to 3.5.15
See changes: https://github.com/cakephp/cakephp/compare/3.6.1...3.5.15
Release notes: https://github.com/cakephp/cakephp/releases/tag/3.5.15
- cakephp/migrations downgraded from 1.8.1 to 1.7.2
See changes: https://github.com/cakephp/migrations/compare/1.8.1...1.7.2
Release notes: https://github.com/cakephp/migrations/releases/tag/1.7.2
> Lock CakePHP to v3.5

- composer.json
- src/ModuleConfig/Parser/V1/Ini/AbstractIniParser.php
Reasons, in no particular order:
* piwik/ini is a GPL-based library.  We prefer MIT.
* piwik/ini is obsolete/abandoned.
* INI file parsing is now kept for backward-compatibility only.
* PHP provides a native INI parser, which is sufficient for BC.
* One less composer dependency to download.
> Removed dependency on piwik/ini

- composer.json
- src/ModuleConfig/PathFinder/V2/ListPathFinder.php
- tests/TestCase/ModuleConfig/Parser/V2/Json/ListParserTest.php
- tests/data/Modules/Foo/lists/local_genders.json
Whenever we use a CSV module from `qobo/cakephp-csv-migrations` we want the system to look for the lists inside the module `lists/` directory.
If nothing was found - to fallback to `modules/Common/lists` directory.
> Module lists fallback (task #5596)

- src/ModuleConfig/PathFinder/BasePathFinder.php
- tests/TestCase/ModuleConfig/ModuleConfigTest.php
The $validate flag was ignored due to changes made in PR #128 . This PR adds a test case for this and fixes the issues.
> Take into consideration the validate flag (task #5597)

- composer.json
This reverts commit 1cb059ed0d56681d7e8f625be83c4868755c0f03.
> Revert "Upgrading cakedc/users plugin to ^6.0 for CakePHP 3.5.x (task #6932)"

- .travis.yml
- composer.json
- phpunit.xml.dist
- tests/TestCase/ModuleConfig/Parser/Schema/SchemaTest.php
- tests/TestCase/ModuleConfig/Parser/V1/Csv/ListParserTest.php
- tests/TestCase/ModuleConfig/Parser/V1/Csv/MigrationParserTest.php
- tests/TestCase/ModuleConfig/Parser/V1/Csv/ViewParserTest.php
- tests/TestCase/ModuleConfig/Parser/V1/Ini/ConfigParserTest.php
- tests/TestCase/ModuleConfig/Parser/V1/Ini/FieldsParserTest.php
- tests/TestCase/ModuleConfig/Parser/V1/Ini/ReportsParserTest.php
- tests/TestCase/ModuleConfig/Parser/V1/Json/MenusParserTest.php
- tests/TestCase/ModuleConfig/Parser/V2/Json/ListParserTest.php
- tests/TestCase/ModuleConfig/Parser/V2/Json/ViewParserTest.php
- tests/TestCase/ModuleConfig/PathFinder/V1/ConfigPathFinderTest.php
- tests/TestCase/ModuleConfig/PathFinder/V1/FieldsPathFinderTest.php
- tests/TestCase/ModuleConfig/PathFinder/V1/ListPathFinderTest.php
- tests/TestCase/ModuleConfig/PathFinder/V1/MigrationPathFinderTest.php
- tests/TestCase/ModuleConfig/PathFinder/V1/ViewPathFinderTest.php
- tests/TestCase/UtilityTest.php
This release drops support for PHP 5.6.  The minimum required version is now PHP 7.1
> Switch from PHP 5.6 to PHP 7.1 (task #7636)

- .travis.yml
- config/bootstrap.php
- phpstan.neon.dist
- src/Model/Behavior/FootprintBehavior.php
- src/ModuleConfig/ModuleConfig.php
- src/ModuleConfig/Parser/AbstractParser.php
- src/ModuleConfig/Parser/V1/Csv/ListParser.php
- src/ModuleConfig/Parser/V1/Csv/MigrationParser.php
- src/ModuleConfig/Parser/V1/Ini/ConfigParser.php
- src/ModuleConfig/Parser/V2/Json/ConfigParser.php
- src/ModuleConfig/Parser/V2/Json/ListParser.php
- src/Utility.php
- src/Utility/Convert.php
- tests/App/Controller/UsersController.php
- tests/TestCase/ModuleConfig/Cache/CacheTest.php
- tests/TestCase/ModuleConfig/ModuleConfigTest.php
- tests/TestCase/ModuleConfig/Parser/V1/Csv/ListParserTest.php
- tests/TestCase/ModuleConfig/Parser/V1/Csv/MigrationParserTest.php
- tests/TestCase/ModuleConfig/Parser/V1/Ini/ConfigParserTest.php
- tests/TestCase/ModuleConfig/Parser/V1/Ini/FieldsParserTest.php
- tests/TestCase/ModuleConfig/Parser/V1/Ini/ReportsParserTest.php
- tests/TestCase/ModuleConfig/Parser/V2/Json/ListParserTest.php
- tests/TestCase/ModuleConfig/Parser/V2/Json/ViewParserTest.php
- tests/TestCase/Utility/ConvertTest.php
- tests/TestCase/UtilityTest.php
* Added `Convert` class to Utilities.
* Moved `valueToBytes()` method to `Convert` class.
* Moved `objectToArray()` method to `Convert` class.
* Added `arrayToObject()` method to `Convert` class.
* Updated codebase (`src/`, `config/`).
* Updated unit tests.
* Fixed all PHPStan errors.
* Enabled PHPStan during TravisCI test runs.
> Utils and PHPStan (task #8244)

- .travis.yml
- composer.json
* Use 3.x branch of cakephp-imagine-plugin
* Use branch-2.0 of cakephp-file-storage from custom fork
* Temporarily disable strict validation of `composer.json`
> Use CakePHP 3.6 compatible burzum plugins (task #8512)

- src/ModuleConfig/Parser/Schema/config.json
Workaround for a bug in the external json validator (https://github.com/justinrainbow/json-schema) which causes default empty objects to be transformed into an empty array, which in turns fails validation when arrays are not specified in the `type` parameter.
> Bugfix for empty obj treated as arrays and validation fails (task #8712)

- src/ModuleConfig/PathFinder/BasePathFinder.php
- src/ModuleConfig/PathFinder/V2/ListPathFinder.php
When loading lists we would skip custom lists defined under the default (Common) module. Previously, the sequence was `ModuleName/lists/list.json -> ModuleName/lists/list.dist.json -> Common/lists/list.dist.json`
The new sequence is `ModuleName/lists/list.json -> ModuleName/lists/list.dist.json -> Common/lists/list.json -> Common/lists/list.dist.json`
> Do not skip non-dist common lists (task #9017)

- webroot/js/dataTables.init.js
Extends the implementation for batch actions (edit, delete) to allow passing the CSRF Token through HTML data attributes. The provided token is added as text input when generating the form to be submitted.
> Add support for CSRF token (task #7073)

- src/ModuleConfig/ModuleConfig.php
- tests/TestCase/ModuleConfig/ModuleConfigTest.php
Add helper methods on ModuleConfig class which can be used to evaluate whether a module exists or has some particular migration fields.
> Add helper methods for testing modules (task #9677)

- src/Model/Behavior/EncryptedFieldsBehavior.php
- tests/App/Model/Entity/User.php
- tests/App/Model/Table/UsersTable.php
- tests/TestCase/Model/Behavior/EncryptedFieldsBehaviorTest.php
- tests/bootstrap.php
Adds an encrypted fields behavior, which allows encrypting/decrypting entity fields using `\Cake\Utility\Security` class.
Has an additional finder method which can return decrypted fields and can be chained with other finders.
> Implement encrypted fields behavior (task #9585)

- src/Model/Behavior/EncryptedFieldsBehavior.php
- tests/TestCase/Model/Behavior/EncryptedFieldsBehaviorTest.php
Fixes a rare bug with field names when global decryption is enabled and no fields are passed to the finder. See test case for details.
> EncryptFieldsBehavior finder fields bug (task #9585)

- composer.json
- config/bootstrap.php
- phpstan.neon.dist
- src/ConfigInterface.php
- src/ModuleConfig/Cache/Cache.php
- src/ModuleConfig/ClassFactory.php
- src/ModuleConfig/ModuleConfig.php
- src/ModuleConfig/Parser/Parser.php
- src/ModuleConfig/Parser/ParserInterface.php
- src/ModuleConfig/Parser/Schema.php
- src/ModuleConfig/Parser/SchemaInterface.php
- src/Utility.php
- tests/TestCase/Model/Behavior/EncryptedFieldsBehaviorTest.php
- tests/TestCase/ModuleConfig/Parser/ParserTest.php
This PR introduces the assertions library while also improves the type hints and checks, mostly by not relying on var annotations. In particular:
* Introduces `ConfigInterface` to be used along with `InstanceConfigTrait` 
* Removes invalid var annotations and unnecessary castings
* Applies more strict type-hints whenever this was possible
> Improve type hints and checks (task #9606)

- phpstan.neon.dist
- src/ModuleConfig/Parser/Schema/reports.json
- src/ModuleConfig/PathFinder/BasePathFinder.php
The `report.json` support now "polarArea", "pieChart", "horizontalBar" charts, plus we can add more options in the configuration for bar, doughnut, line, polarArea, pie and horizontalBar.
> Update json schema for the new charts (task #10422)

- src/ModuleConfig/Parser/Schema/fields.json
Following extension to `fields` schema will allow `qobo/cakephp-csv-migrations` to use Cloud adapters (like S3 Buckets) for handling file uploads using `burzum/cakephp-file-storage` plugin.
We allow developers to define which file field will be using Local or S3 file upload adapters in csv modules.
> Expanding field configurations with fileUploadAdapter (task #11014)

- composer.json
The latest changes in CakePHP Imagine plugin have increased the minimum CakePHP version from 3.6 to 3.7.
This PR locks the version to the latest commit to maintain support for CakePHP 3.6
> Lock version for CakePHP Imagine plugin

- src/ModuleConfig/Parser/Parser.php
* Note: All JSON files will needed to be carefully inspected for potential inconsistencies, due to JSON default issues deriving from the `json-schema` package.
Possible restoration of this functionality should be considered once `v6.0.0` of `json-schema` is released.
> Disabling defaults substitution (task #10956)

- config/module_config.php
- src/ModuleConfig/Cache/Cache.php
- src/ModuleConfig/PathFinder/BasePathFinder.php
- tests/TestCase/ModuleConfig/Cache/CacheTest.php
- tests/config/module_config.php
Caching engine can now be configured on app level. It is also possible to completely disable the file lookup for non dist files, to avoid un-necessary actions when only dist files are in use.
> Caching improvements for ModuleConfig (task #14655)

- .gitignore
- phpcs.xml.dist
- phpstan.neon.dist
- src/Module/Exception/InvalidClassException.php
- src/Module/Exception/MissingModuleException.php
- src/Module/Module.php
- src/Module/ModuleInterface.php
- src/Module/ModuleRegistry.php
- src/Shell/GenerateModulesShell.php
- src/Shell/Task/ModuleTask.php
- src/Template/Bake/module.twig
- tests/TestCase/ModuleConfig/Parser/ListParserTest.php
- tests/TestCase/Shell/Task/ModuleTaskTest.php
- tests/bootstrap.php
Generating php classes from json files allows us to generate modules during deployment and avoid reading/parsing json hundreds of times per script execution on production environments
> Generate php modules from json files (task #16415)

- src/ModuleConfig/Parser/Schema/config.json
This change allows us to define multiple parents for a module. 
It's quite useful for aggregate tables, or those that have more than one foreign key in a table.
```
"parent": [
{
"module": "ParentA",
"relation": "parent_a_id",
"redirect": "parent"
},
{
"module": "ParentB",
"relation": "parent_b_id",
"redirect": "parent"
}
]
```
Upon saving the record, we would be able to pick the redirect from the module.
> Allow specifying multiple parents (task #16553)

- src/ModuleConfig/Parser/Schema/fields.json
Adding `limits` definition that's quite handy for aggregate fields that might link to multiple entities, like file uploads.
> Adding limits field property

- src/ModuleConfig/PathFinder/V2/ListPathFinder.php
- tests/TestCase/ModuleConfig/ModuleConfigTest.php
List fallbacks have been disabled with the introduction of `ModuleRegistry`. To make things more consistent, we are removing the fallback support from Finder and Parser classes.
> Remove lists fallback (task #16882)

- composer.json
This PR defines v3.8 as the minimum CakePHP version acceptable and fixes most of the deprecation warnings.
> Support for CakePHP v3.8
