QoboLtd/cakephp-utils

- composer.json
- config/bootstrap.php
- config/file_storage.php
- Composer require common plugins.
- Load default plugins configuration.
> Common plugins (task #3309)

- tests/TestCase/Parser/Ini/ParserTest.php
- tests/data/Modules/Foo/config/fields.ini
Fields.ini functionality wasn't covered by PHPUnit
> Added more Parser tests for fields.ini

- composer.json
Added new composer packages, modified existing package versions
> Composer changes (task #3309)

- src/PathFinder/FieldsPathFinder.php
- tests/TestCase/PathFinder/FieldsPathFinderTest.php
Renamed `FieldsIniPathFinder` to `FieldsPathFinder`.
> Renamed to FieldsPathFinder (task #2970)

- config/bootstrap.php
Added global function for converting php file sizes to byte integers.
> Size to bytes

- src/ModuleConfig/Parser/Ini/AbstractIniParser.php
* Do not validate empty data
* Properly add validation errors to parser errors
> Minor fixes to AbstractIniParser (task #3495)

- src/ModuleConfig/ModuleConfig.php
- src/ModuleConfig/Parser/Json/AbstractJsonParser.php
- src/ModuleConfig/Parser/Json/MenusParser.php
- src/ModuleConfig/Parser/Schema/menus.json
- src/ModuleConfig/PathFinder/MenusPathFinder.php
- tests/TestCase/ModuleConfig/Parser/Json/MenusParserTest.php
- tests/data/Modules/Foo/config/menus.json
Menus configuration file is a new addition to the modules
configuration, which allows to define menu options and items.
This is the first configuration file to use the JSON format.  The
code base was created from copy-paste-modify of Config path finder
and parser.  Once we start moving more and more to JSON, a lot of
this specific code will move to the AbstractParser.
> Added Menus path finder and parser (task #3495) (task #809)

- src/ModuleConfig/ModuleConfig.php
- src/ModuleConfig/Parser/AbstractParser.php
- src/ModuleConfig/Parser/Csv/AbstractCsvParser.php
- src/ModuleConfig/Parser/Csv/ListParser.php
- src/ModuleConfig/Parser/Csv/MigrationParser.php
- src/ModuleConfig/Parser/Csv/ViewParser.php
- src/ModuleConfig/Parser/Ini/AbstractIniParser.php
- src/ModuleConfig/Parser/Json/AbstractJsonParser.php
- tests/TestCase/ModuleConfig/ModuleConfigTest.php
- tests/TestCase/ModuleConfig/Parser/Csv/ListParserTest.php
- tests/TestCase/ModuleConfig/Parser/Csv/ViewParserTest.php
- tests/TestCase/ModuleConfig/Parser/Ini/ConfigParserTest.php
- tests/TestCase/ModuleConfig/Parser/Json/MenusParserTest.php
- tests/data/Modules/Foo/config/config_bad.ini
Fixes for parsing and finding files.
> Bugfixes (task #3495)

- src/ModuleConfig/Parser/Schema/fields.json
* format, used for time stamp fields
* precision, used for numeric fields
* linkTarget, used for URL and Link fields
* linkTo, used for Link fields
> Added more options for fields.ini (task #3809)

- .travis.yml
> Merged with cakephp-plugin-tempate v3.3.0 (task #3899)

- config/bootstrap.php
- config/colors.php
- src/Utility.php
- tests/TestCase/UtilityTest.php
- tests/bootstrap.php
- tests/config/colors.php
Adding generic dropdown options for color configs.
> Adding getColors method for Select2(task #3873)

- src/ModuleConfig/ModuleConfig.php
- src/ModuleConfig/Parser/Csv/MigrationParser.php
- src/ModuleConfig/Parser/Csv/ViewParser.php
- src/ModuleConfig/Parser/Ini/ConfigParser.php
- src/ModuleConfig/Parser/Ini/FieldsParser.php
- src/ModuleConfig/Parser/Ini/ReportsParser.php
- src/ModuleConfig/Parser/Json/MenusParser.php
- src/ModuleConfig/Parser/Schema/config.json
* Added 'translatable' flag to config.ini
* Fixed minor issues identified by PHPStan
> Added 'translatable' flag to config.ini (task #4001)

- config/file_storage.php
- src/ErrorTrait.php
- src/ModuleConfig/ModuleConfig.php
- src/ModuleConfig/Parser/AbstractParser.php
- src/ModuleConfig/Parser/Csv/AbstractCsvParser.php
- src/ModuleConfig/Parser/Csv/ViewParser.php
- src/ModuleConfig/Parser/Ini/AbstractIniParser.php
- src/ModuleConfig/Parser/Ini/ConfigParser.php
- src/ModuleConfig/Parser/Json/AbstractJsonParser.php
- src/ModuleConfig/PathFinder/BasePathFinder.php
- src/ModuleConfig/PathFinder/ListPathFinder.php
- src/ModuleConfig/PathFinder/ViewPathFinder.php
A few minor code improvements based on the [BetterCodeHub analysis and report](https://bettercodehub.com/results/QoboLtd/cakephp-utils):
* Removed duplication in configuration of thumbnail sizes.
* Refactored and simplified the setting of defaults in Config parser.
* More accurate error/warnings reporting.
* Refactored common code into `ErrorTrait`.
> Minor refactoring (task #4002)

- src/ModuleConfig/Parser/Ini/ConfigParser.php
- src/ModuleConfig/Parser/Schema/config.json
Parameter - parent_modules contains comma separated list of parent modules for current one.
> Added new config.ini parameter - parent_modules to specify parents - task #4178

- composer.json
myclabs/php-enum [:link:](https://github.com/myclabs/php-enum)
> Require myclabs/php-enum library (task #4352)

- webroot/css/select2-style.css
Target all select2 selection types
> AdminLTE upgrade (task #4371)

- src/ModuleConfig/Parser/AbstractParser.php
- src/ModuleConfig/Parser/Csv/AbstractCsvParser.php
- src/ModuleConfig/Parser/Csv/ListParser.php
- src/ModuleConfig/Parser/Csv/ViewParser.php
- src/ModuleConfig/Parser/Ini/AbstractIniParser.php
- src/ModuleConfig/Parser/Json/AbstractJsonParser.php
More refactoring and code simplification based on the Better Code Hub reports.
> Refactoring

- webroot/js/dataTables.init.js
Moved DataTables initialize logic on the global scope, to allow multiple initializations and prevent options overwrite.
> DataTables initialize logic (task #4700)

- src/ModuleConfig/ModuleConfig.php
- src/ModuleConfig/Parser/AbstractParser.php
- src/ModuleConfig/Parser/Csv/AbstractCsvParser.php
- src/ModuleConfig/Parser/Csv/ListParser.php
- src/ModuleConfig/Parser/Csv/MigrationParser.php
- src/ModuleConfig/Parser/Csv/ViewParser.php
- src/ModuleConfig/Parser/Ini/AbstractIniParser.php
- src/ModuleConfig/Parser/Ini/ConfigParser.php
- src/ModuleConfig/Parser/Ini/FieldsParser.php
- src/ModuleConfig/Parser/Ini/ReportsParser.php
- src/ModuleConfig/Parser/Json/AbstractJsonParser.php
- src/ModuleConfig/Parser/Json/MenusParser.php
Fixing issues identified by PHPStan
> Fixed incorrect references to stdClass

- .codeclimate.yml
Updated to [cakephp-plugin-template v4.0.1](https://github.com/QoboLtd/cakephp-plugin-template/releases/tag/v4.0.1).
> Template update

- src/ErrorAwareInterface.php
- src/ModuleConfig/Cache/Cache.php
- src/ModuleConfig/ModuleConfig.php
- src/ModuleConfig/Parser/ParserInterface.php
- src/ModuleConfig/PathFinder/PathFinderInterface.php
- src/Utility/FileLock.php
* Fixing some issues identified by PHPStan.
* Adding more law and order to interfaces.
> Minor fixes

- composer.json
Updating `composer.json` to CakePHP 3.5.
> CakePHP 3.5 (task #4383)

- webroot/js/dataTables.init.js
Extended the functionality to handle client-side API responses format.
Requires release of PR: https://github.com/QoboLtd/project-template-cakephp/pull/408
> DataTables init logic extension (task #4928)

- composer.json
- config/locker.php
- src/Utility/Locker/BaseLocker.php
- src/Utility/Locker/FileLocker.php
- src/Utility/Locker/LockerInterface.php
- tests/TestCase/Utility/Locker/FileLockerTest.php
- added new library to make lock - ninja-mutex;
- reorganize lock classes to add later more lock types
> Improve locker - task #5054

- .travis.yml
- LICENSE
- composer.json
Updated to [cakephp-plugin-template v4.1.0](https://github.com/QoboLtd/cakephp-plugin-template/releases/tag/v4.1.0).
> Updated to cakephp-plugin-template v4.1.0

- src/Utility.php
- tests/TestCase/UtilityTest.php
We analyse controllers directory and build api
paths and prefixes in ascending order for the app's
later use.
> Adding API versions tree collector (task #5385)

- src/Utility.php
- src/Utility/Salt.php
- tests/TestCase/Utility/SaltTest.php
- tests/TestCase/UtilityTest.php
* Added utility Salt class which helps with reading, writing, and generating random security salt strings, using files as storage.
* Minor improvements to path checking.
> Random salt (task #5518)

- composer.json
Above behavior allows quickly duplicate the entries
with its related models.
> Adding duplicatable behavior (task #5575)

- composer.json
Updated [CRUD](https://github.com/friendsofcake/crud) plugin to [v5.*](https://github.com/FriendsOfCake/crud/releases/tag/5.4.1)
> Updated CRUD plugin to v5.* (task #4569)

- webroot/js/dataTables.init.js
* Added pagination option for listing 5 entries.
* Set default pagination option to 10 entries.
> DataTable pagination options (task #6459)

- composer.json
CakePHP Swagger plugin [releases](https://github.com/alt3/cakephp-swagger/releases)
> Upgraded alt3 cakephp-swagger plugin to v2.* (task #6686)

- webroot/plugins/daterangepicker/css/daterangepicker.css
- webroot/plugins/daterangepicker/js/daterangepicker.js
Added date-time picker JS library v3.0.3
Links:
https://github.com/dangrossman/daterangepicker
http://www.daterangepicker.com
> Added date-time picker JS library (task #6728)

- composer.json
This reverts commit 238bb207f1afdce136ec8b7673d22e1eefd7978a.
> Revert "Revert "Upgrading cakedc/users plugin to ^6.0 for CakePHP 3.5.x (task #6932)""

- composer.json
* Upgraded muffin/trash to v2.*
* Upgraded lorenzo/audit-stash to v2.*
> Upgraded plugins to CakePHP 3.6 compatible versions (task #8175)

- .editorconfig
- .gitattributes
- .gitignore
- .stickler.yml
- .travis.yml
- composer.json
- config/bootstrap.php
- config/locker.php
- phpcs.xml.dist
- phpstan.neon.dist
- phpunit.xml.dist
- tests/config/routes.php
* Updated to [cakephp-plugin-template v5.1.0](https://github.com/QoboLtd/cakephp-plugin-template/releases/tag/v5.1.0).
* Updated `composer.json`
* Fixed PHP CodeSniffer warnings
> Merged cakephp-plugin-template v5.1.0

- tests/App/Controller/UsersController.php
- tests/bootstrap.php
Updated to [cakephp-plugin-template v5.1.1](https://github.com/QoboLtd/cakephp-plugin-template/releases/tag/v5.1.1).
> Merged cakephp-plugin-template v5.1.1

- composer.json
- phpcs.xml.dist
- tests/App/Application.php
- tests/App/Controller/AppController.php
- tests/bootstrap.php
* Updated to [cakedc/users v7+](https://github.com/CakeDC/users/releases).
* Merged [qobo/cakephp-plugin-template v5.2.1](https://github.com/QoboLtd/cakephp-plugin-template/releases/tag/v5.2.1).
> Updates (task #8244)

- src/TestSuite/Utility.php
Added two methods to help test private methods from phpunit tests
> Added two methods to help test private methods from phpunit tests (task #8430)

- src/ModuleConfig/Parser/Schema/config.json
> Trash behavior (task #2536)

- src/ModuleConfig/Parser/Schema/view.json
Bring back support for embedded fields into view json schema.
> Bring back support for embedded fields into view json schema (task #8712)

- src/ModuleConfig/Parser/Schema/config.json
Restore missing default values from `config.json` schema.
> Restore missing default values into config schema (task #8712)

- src/ModuleConfig/Parser/Schema/view.json
Remove `uniqueItems` from view schema
> Remove `uniqueItems` from view schema (task #9483)

- composer.json
https://github.com/CakeDC/users/releases
> Upgraded CakeDC Users plugin to v8.* (task #9557)

- src/ModuleConfig/Parser/ListParser.php
- src/ModuleConfig/Parser/Schema/list.json
- tests/data/Modules/Foo/lists/local_genders.json
Update the list schema to accept only boolean values in the `inactive` field definition.
> List schema improvements (task #9739)

- src/Model/Behavior/EncryptedFieldsBehavior.php
- tests/TestCase/Model/Behavior/EncryptedFieldsBehaviorTest.php
Improve EncryptedFieldsBehavior by decreasing nesting level and moving the table field check to a more appropriate place, which will ensure all decryption methods function in the same manner.
> EncryptedFieldsBehavior QoL improvements (task #9585)

- src/ModuleConfig/Parser/Schema/fields.json
- **min** value for field
- **step** to increase/decrease field value
> Added new field properties (task #10322) 

- src/ModuleConfig/Parser/Schema/view.json
Improves the existing validation for relation fields by allowing only strings matching a particular pattern (similar to EMBEDDED)
> Improve JSON schema for relation fields (task #10567)

- src/ModuleConfig/Parser/Schema/reports.json
Add `finders` in Json parser as object.
> Add finders in Json parser (task #10667)

- src/Utility.php
- tests/TestCase/UtilityTest.php
Resolves the phpstan errors here: https://travis-ci.org/QoboLtd/cakephp-roles-capabilities/jobs/560888474
> Use string type array declaration (task #11200)

- src/Plugin.php
- tests/TestCase/Model/Behavior/EncryptedFieldsBehaviorTest.php
- tests/TestCase/UtilityTest.php
- tests/bootstrap.php
- tests/config/module_config.php
This PR fixes the existing deprecation warnings by adjusting fixture names, introducing the `Plugin` class and adjusting config for tests.
> Fix Deprecation Warnings (task #13517)

- composer.json
We use a custom package to include the fix for JFIF
> Add support for JFIF (task #16837)

- src/Shell/Task/ModuleTask.php
- tests/App/SampleModuleDecorator.php
- tests/TestCase/Shell/Task/ModuleTaskTest.php
Add support for decorating module payloads during file generation
> Module decorators (task #16959)

- src/ModuleConfig/Parser/Schema/view.json
* Back-port changes for virtual fields on view schema from the master
> Provision for embedding virtual fields (task #16980)

- config/icons.php
We define the default icons prefix to `fa fa-`
> Define icons prefix (task #17609)

- src/Shell/GenerateModulesShell.php
Solving an issue where decorators require modules, that not exist yet.
> Apply decorators later in generation process (Task #17470)

- src/ModuleConfig/Parser/Schema/view.json
We are removing cols constraint to allow views to handle this
> Remove cols constraint (task #17480)

- webroot/js/dataTables.init.js
Update datatables dom rendering, pagination, added callback to show/hide pagination and apply responsive for table
> Update datatable init

- src/Shell/GenerateModulesShell.php
- src/Shell/Task/ModuleTask.php
Add support for outputting modules outside src eg. cake generate_modules --output-path build
> Added support for overriding modules output path

- src/ModuleConfig/Parser/Schema/fields.json
- webroot/js/dataTables.init.js
These two attributes will be used for the related lookup fields
> Add two more attributes in the fields schema (Task #19430)

- src/ModuleConfig/Parser/Schema/config.json
Allow to exclude some fields during the conversion
> Exclude fields during conversion (Task #19443)
